name       : gumbo-parser
version    : 0.10.1
release    : 1
source     :
    - https://github.com/google/gumbo-parser/archive/v0.10.1.tar.gz : 28463053d44a5dfbc4b77bcf49c8cee119338ffa636cc17fc3378421d714efad
license    : Apache-2.0
component  : programming.library
summary    : An HTML5 parsing library in pure C99
description: |
    Gumbo is an implementation of the HTML5 parsing algorithm implemented as a pure C99 library with no outside dependencies.
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
